src/Entity/User.php
<?php

namespace App\Entity;

use App\Traits\EntityUseTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt")
 * @Vich\Uploadable()
 * @ORM\Table(name="`user`")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 * @UniqueEntity("contact")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface, \Serializable
{
    use EntityUseTrait;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=225)
     * @Assert\NotBlank
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $first = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateN;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=14, max=30)
     */
    private $contact;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isOnline = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fonction;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLogin;

    /**
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="imageName")
     * @var File|null
     * @Assert\Image(
     *     maxSize = "200k",
     *     maxSizeMessage = "Veuillez soumettre des fichiers qui n'excédent pas 200K.",
     *     mimeTypes={"image/png", "image/jpeg", "image/jpg"},
     *     mimeTypesMessage = "Veuillez soumettre des fichiers de type (png , jpeg, jpg)."
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Groupe", inversedBy="user")
     */
    protected $groupe;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", inversedBy="users")
     * @Assert\NotBlank
     */
    private $userRoles;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="users")
     */
    private $service;

    public function __construct()
    {
        $this->groupe = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateN(): ?\DateTimeInterface
    {
        return $this->dateN;
    }

    public function setDateN(?\DateTimeInterface $dateN): self
    {
        $this->dateN = $dateN;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setContact(string $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    public function getIsOnline(): ?string
    {
        return $this->isOnline;
    }

    public function setIsOnline(string $isOnline): self
    {
        $this->isOnline = $isOnline;

        return $this;
    }

    public function getFonction(): ?string
    {
        return $this->fonction;
    }

    public function setFonction(?string $fonction): self
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFirst(): ?bool
    {
        return $this->first;
    }

    public function setFirst(bool $first): self
    {
        $this->first = $first;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /**
     *
     * @return array|string
     */
    public function getRoles()
    {
        $role = [];
        foreach ($this->getGroupe() as $value) {
            $role[] = $value->getRole();
        }
        return $role;
    }



    /**
     * @return string|null The salt
     */
    public function getSalt() 
    {
        return null;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @link https://php.net/manual/en/class.serializable.php
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password
        ]);
    }
    
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password
        ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return  File|null
     */ 
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return self
     */ 
    public function setImageFile(?File $imageFile): User
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \Datetime('now');
        }
        return $this;
    }

    /**
     * @return string
     */ 
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * @param string $imageName
     * @return self
     */ 
    public function setImageName(?string $imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return Collection|Groupe[]
     */
    public function getGroupe(): Collection
    {
        return $this->groupe;
    }

    public function addGroupe(Groupe $groupe): self
    {
        if (!$this->groupe->contains($groupe)) {
            $this->groupe[] = $groupe;
        }

        return $this;
    }

    public function removeGroupe(Groupe $groupe): self
    {
        if ($this->groupe->contains($groupe)) {
            $this->groupe->removeElement($groupe);
        }

        return $this;
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
        }

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function __toString()
    {
       return $this->nom." ".$this->prenom; 
    }
     
    public function getIsDelete()
    {
        $etat = true;
        return $etat;
    }

    public function getCode(): ?string
    {
        return 'USE'.$this->id;
    }
}

src/Form/ObligationType.php
<?php

namespace App\Form;

use App\Entity\Sgi;
use App\Entity\Emetteur;
use App\Entity\Obligation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;

class ObligationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('sgi', EntityType::class, [
                'required' => true,
                'label' => false,
                'class' => Sgi::class,
                'choice_label' => 'nom',
                'multiple' => false,
                'attr' => [
                    'placeholder' => "SGI"
                ]
            ])
            ->add('libelle', TextType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "Nom"
                ]
            ])
            ->add('emetteur', EntityType::class, [
                'required' => true,
                'label' => false,
                'class' => Emetteur::class,
                'choice_label' => 'nom',
                'multiple' => false,
                'attr' => [
                    'placeholder' => "Emetteur"
                ]
            ])
            ->add('duree', ChoiceType::class, [
                'label' => false,
                'choices' => [
                    1 => 1,
                    2 => 2,
                    3 => 3,
                    4 => 4,
                    5 => 5,
                    6 => 6,
                    7 => 7,
                    8 => 8,
                    9 => 9,
                    10 => 10,
                    11 => 11,
                    12 => 12,
                    13 => 13,
                    14 => 14,
                    15 => 15,
                    16 => 16,
                    17 => 17,
                    18 => 18,
                    19 => 19,
                    20 => 20
                ]
            ])
            ->add('interet', PercentType::class, [
                'label' => false,
                'attr' => [
                    'min' => 0,
                    'placeholder' => "Taux d'intérêt"
                ]
            ])
            ->add('nominal', IntegerType::class, [
                'label' => false,
                'attr' => [
                    'min' => 0,
                    'class' => 'nominal',
                    'placeholder' => "Montant nominal"
                ]
            ])
            ->add('montant', IntegerType::class, [
                'label' => false,
                'attr' => [
                    'min' => 0,
                    'class' => 'montant text-danger font-weight-bold',
                    'placeholder' => "Montant souscrit",
                    'readonly' => true
                ]
            ])
            ->add('type', ChoiceType::class, [
                'label' => false,
                'choices' => [
                    'AMORTISSEMENT CONSTANT' => 'AMORTISMENT',
                    'IN FINE' => 'FINE',
                    'ANNUITES CONSTANTES' => 'CONSTANTE'
                ]
            ])
            ->add('grace', DateType::class, [
                'label' => false,
                'widget' => 'single_text',
                'empty_data'  => ''
            ])
            ->add('date', DateType::class, [
                'label' => false,
                'widget' => 'single_text',
                'empty_data'  => ''
            ])
            ->add('nbr', IntegerType::class, [
                'label' => false,
                'attr' => [
                    'min' => 0,
                    'placeholder' => "Nombre de rembousement"
                ]
            ])
            ->add('souscrit', IntegerType::class, [
                'label' => false,
                'attr' => [
                    'min' => 0,
                    'class' => 'souscrit',
                    'placeholder' => "Nbr d'obligation souscrit"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Obligation::class,
        ]);
    }
}

templates/obligation/_delete_form.html.twig
<form style="display:inline-block" method="post" action="{{ path('obligation_delete', {'id': obligation.id}) }}"
 onsubmit="return confirm('Êtes vous vraiment sur ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ obligation.id) }}">
    <button class="btn btn-danger">Supprimer <i data-feather="trash-2"></i></button>
</form>

templates/obligation/_form.html.twig
<div class="form-group row">
    <label for="{{ form.libelle.vars.id }}" class="col-sm-3 text-right">
        Nom <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.libelle) }}
        <div class="form-error">{{ form_errors(form.libelle) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.emetteur.vars.id }}" class="col-sm-3 text-right">
        Emetteur <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.emetteur) }}
        <div class="form-error">{{ form_errors(form.emetteur) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.date.vars.id }}" class="col-sm-3 text-right">
        Date <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.date) }}
        <div class="form-error">{{ form_errors(form.date) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.duree.vars.id }}" class="col-sm-3 text-right">
        Durée <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.duree) }}
        <div class="form-error">{{ form_errors(form.duree) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.nominal.vars.id }}" class="col-sm-3 text-right">
        Montant nominal <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.nominal) }}
        <div class="form-error">{{ form_errors(form.nominal) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.souscrit.vars.id }}" class="col-sm-3 text-right">
        Nbr d'obligation souscrit <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.souscrit) }}
        <div class="form-error">{{ form_errors(form.souscrit) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.montant.vars.id }}" class="col-sm-3 text-right">
        Montant souscrit <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.montant) }}
        <div class="form-error">{{ form_errors(form.montant) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.interet.vars.id }}" class="col-sm-3 text-right">
        Taux d'intérêt <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.interet) }}
        <div class="form-error">{{ form_errors(form.interet) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.type.vars.id }}" class="col-sm-3 text-right">
        Plan d'amortissement <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.type) }}
        <div class="form-error">{{ form_errors(form.type) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.grace.vars.id }}" class="col-sm-3 text-right">
        Période de grâce <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.grace) }}
        <div class="form-error">{{ form_errors(form.grace) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.nbr.vars.id }}" class="col-sm-3 text-right">
        Nombre de rembousement <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.nbr) }}
        <div class="form-error">{{ form_errors(form.nbr) }}</div>
    </div>
</div>
<div class="form-group row">
    <label for="{{ form.sgi.vars.id }}" class="col-sm-3 text-right">
        SGI concerné <span class="exterix">*</span>
    </label>
    <div class="col-sm-7">
        {{ form_widget(form.sgi) }}
        <div class="form-error">{{ form_errors(form.sgi) }}</div>
    </div>
</div>

templates/obligation/_index.html.twig
{% for obligation in obligations %}   
    <div class="col-md-6 my-1">
        <a href="{{ path('obligation_show', {'id': obligation.id}) }}" style="text-decoration: none;">
            <div class="card shadow-sm border-{{param.theme}}">
                <div class="card-body">
                    Nom : {{ obligation.libelle }}
                    <h4 class="card-title text-primary">Emetteur : {{ obligation.emetteur.nom }}</h4>
                    <h6 class="card-title text-primary text-muted">  
                        <div class="row">
                            <div class="col-md-6">
                                Nombre d'obligations : {{ obligation.nbr|number_format(0, ' ', ' ') }}
                            </div>
                            <div class="col-md-6">
                                Montant : {{ obligation.montant|number_format(0, ' ', ' ')|
                                    color({'color': 'warning', 'class': 'font-weight-bold', 'content': param.sym}) }}
                            </div>
                        </div> 
                        <div class="row mt-2">
                            <div class="col-md-6 text-primary">
                                Intérêt : {{ obligation.interet }} ({{ obligation.interet * 100 }} %)
                            </div>
                            <div class="col-md-6 text-primary">
                                Durée : {{ obligation.duree }} ans
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6">
                                Période de grâce : {{ obligation.grace|date('d-m-Y') }}
                            </div>
                            <div class="col-md-6">
                                Nominal : {{ obligation.nominal }}
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md">
                                Type : {{ obligation.typel }}
                            </div>
                        </div>
                    </h6>
                    <div class="float-right">
                        <div class="btn-group">
                            <a href="{{ path('obligation_show', {'id': obligation.id}) }}" class="secondary" data-tooltip data-placement="top" title="Détail">
                                <i data-feather="file-minus"></i>
                            </a>
                            <a class="text-info" href="{{ path('obligation_edit', {'id': obligation.id}) }}" data-tooltip data-placement="left" title="Supprimer">
                                <i data-feather="edit"></i>
                            </a>
                        </div>
                        <small class="text-muted">{{obligation.code}}</small>
                    </div>
                </div>
            </div>
        </a>
    </div>
{% endfor %}

templates/obligation/_menu.html.twig
<div class="col-md-3">
    <div class="card border-{{param.theme}}">
        <div class="card-body">
            <h5 class="card-title" align="center">Obligation <i data-feather="archive"></i></h5>
            <div class="sidebar">
                <div class="list-group">
                    <a href="{{ path('home_obligation') }}" class="btn-sm btn btn-{% if route == 'home_obligation' %}outline-{% endif %}{{param.theme}} alignmenu">
                        <i data-feather="pie-chart"></i> Tableau de bord
                    </a>
                    <a href="{{ path('obligation_new') }}" class="btn-sm btn btn-{% if route == 'obligation_new' %}outline-{% endif %}{{param.theme}} mt-1 alignmenu">
                        <i data-feather="plus-circle"></i> Ajouter une obligation
                    </a>
                    <a href="{{ path('obligation_index') }}" class="btn-sm btn btn-{% if route == 'obligation_index' %}outline-{% endif %}{{param.theme}} mt-1 alignmenu">
                        <i data-feather="list"></i> Liste des obligations
                    </a>
                    <a href="{{ path('obligation_situation') }}" class="btn-sm btn btn-{% if route == 'obligation_situation' %}outline-{% endif %}{{param.theme}} mt-1 alignmenu">
                        <i data-feather="package"></i> Situations sorties
                    </a>
                    <a href="{{ path('obligation_situation_non') }}" class="btn-sm btn btn-{% if route == 'obligation_situation_non' %}outline-{% endif %}{{param.theme}} mt-1 alignmenu">
                        <i data-feather="package"></i> Situations non sorties
                    </a>
                    <a href="#" class="btn-sm btn btn-{% if route == '#' %}outline-{% endif %}{{param.theme}} mt-1 alignmenu">
                        <i data-feather="loader"></i> Valorisation
                    </a>
                </div>        
            </div>        
        </div>
    </div>
</div>

templates/obligation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Obligation{% endblock %}

{% block body %}
    <h1>Edit Obligation</h1>

    {{ include('obligation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('obligation_index') }}">back to list</a>

    {{ include('obligation/_delete_form.html.twig') }}
{% endblock %}

templates/obligation/home.html.twig
{% extends "base.html.twig" %}

{% block title %} {{title}} {% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('homepage') }}">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <i data-feather="pie-chart"></i> {{title}}
            </li>
        </ol>
    </nav>
{% endblock %}

{% block body %}
    <div class="row mt-2">

        {{ include('obligation/_menu.html.twig') }}
        
        <div class="col-md-9">
            <div class="row">
            </div>
        </div>
    </div>
{% endblock %}

templates/obligation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{title}} {% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('homepage') }}">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('home_obligation') }}">
                    <i data-feather="pie-chart"></i> Tableau de bord
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
        </ol>
    </nav>
{% endblock %}

{% block body %}
    <div align="right">
        <a href="{{ path('obligation_index') }}" class="btn btn-warning text-white" data-tooltip
         data-placement="top" title="Retour">
            <i data-feather="arrow-left-circle"></i> Retour 
        </a>
    </div>

    <div class="row mt-2">
        {{ include('obligation/_menu.html.twig') }}

        <div class="col-md-9">

            {{ include('default/filtre/filtre.html.twig') }}

            {% for message in app.flashes('success') %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong> 
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}

            <div class="row">
                {{ include('obligation/_index.html.twig') }}
            </div>
        </div>
    </div> 

{% endblock %}

templates/obligation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{title}} {% endblock %}

{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ path('homepage') }}">
                    <i data-feather="home"></i>
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('home_obligation') }}">
                    <i data-feather="pie-chart"></i> Tableau de bord
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('obligation_index') }}">Liste des obligations</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
        </ol>
    </nav>
{% endblock %}

{% block body %}
    <div align="right">
        <a href="{{ path('obligation_index') }}" class="btn btn-warning text-white" data-tooltip
         data-placement="top" title="Retour">
            <i data-feather="arrow-left-circle"></i> Retour 
        </a>
    </div>

    <div class="row mt-2">
        {{ include('obligation/_menu.html.twig') }}

        <div class="col-md-9">
            {{form_start(form)}}
                <div class="card border-{{param.theme}}">
                    <div class="card-header border-{{param.theme}}">
                        <h4>{{title}}</h4>
                    </div>
                    <div class="card-body">
                        {{ include('obligation/_form.html.twig') }}
                        {{ form_rest(form) }}                            
                        <p style="text-align:right;color:red;font-size:12px;">
                            L'astérisque signifie que le champ à renseigner est obligatoire (✱)
                        </p>                      
                    </div>
                </div>
                <button class="btn btn-{{param.theme}} mt-2 float-right">
                    {{button|default('Enrégistrer')}} <i data-feather="save"></i>
                </button>
            {{form_end(form)}}
        </div>
    </div> 

{% endblock %}